package game.entity.pokemon;

public enum PokemonID {
    BULBASAUR("Bulbasaur", 1, new PokemonType[]{PokemonType.GRASS, PokemonType.POISON}),
    IVYSAUR("Ivysaur", 2, new PokemonType[]{PokemonType.GRASS, PokemonType.POISON}),
    VENUSAUR("Venusaur", 3, new PokemonType[]{PokemonType.GRASS, PokemonType.POISON}),
    CHARMANDER("Charmander", 4, new PokemonType[]{PokemonType.FIRE}),
    CHARMELEON("Charmeleon", 5, new PokemonType[]{PokemonType.FIRE}),
    CHARIZARD("Charizard", 6, new PokemonType[]{PokemonType.FIRE, PokemonType.FLYING}),
    SQUIRTLE("Squirtle", 7, new PokemonType[]{PokemonType.WATER}),
    WARTORTLE("Wartortle", 8, new PokemonType[]{PokemonType.WATER}),
    BLASTOISE("Blastoise", 9, new PokemonType[]{PokemonType.WATER}),
    CATERPIE("Caterpie", 10, new PokemonType[]{PokemonType.BUG}),
    METAPOD("Metapod", 11, new PokemonType[]{PokemonType.BUG}),
    BUTTERFREE("Butterfree", 12, new PokemonType[]{PokemonType.BUG, PokemonType.FLYING}),
    WEEDLE("Weedle", 13, new PokemonType[]{PokemonType.BUG, PokemonType.POISON}),
    KAKUNA("Kakuna", 14, new PokemonType[]{PokemonType.BUG, PokemonType.POISON}),
    BEEDRILL("Beedrill", 15, new PokemonType[]{PokemonType.BUG, PokemonType.POISON}),
    PIDGEY("Pidgey", 16, new PokemonType[]{PokemonType.NORMAL, PokemonType.FLYING}),
    PIDGEOTTO("Pidgeotto", 17, new PokemonType[]{PokemonType.NORMAL, PokemonType.FLYING}),
    PIDGEOT("Pidgeot", 18, new PokemonType[]{PokemonType.NORMAL, PokemonType.FLYING}),
    RATTATA("Rattata", 19, new PokemonType[]{PokemonType.NORMAL}),
    RATICATE("Raticate", 20, new PokemonType[]{PokemonType.NORMAL}),
    SPEAROW("Spearow", 21, new PokemonType[]{PokemonType.NORMAL, PokemonType.FLYING}),
    FEAROW("Fearow", 22, new PokemonType[]{PokemonType.NORMAL, PokemonType.FLYING}),
    EKANS("Ekans", 23, new PokemonType[]{PokemonType.POISON}),
    ARBOK("Arbok", 24, new PokemonType[]{PokemonType.POISON}),
    PIKACHU("Pikachu", 25, new PokemonType[]{PokemonType.ELECTRIC}),
    RAICHU("Raichu", 26, new PokemonType[]{PokemonType.ELECTRIC}),
    SANDSHREW("Sandshrew", 27, new PokemonType[]{PokemonType.GROUND}),
    SANDSLASH("Sandslash", 28, new PokemonType[]{PokemonType.GROUND}),
    NIDORAN_FEMALE("Nidoran♀", 29, new PokemonType[]{PokemonType.POISON}),
    NIDORINA("Nidorina", 30, new PokemonType[]{PokemonType.POISON}),
    NIDOQUEEN("Nidoqueen", 31, new PokemonType[]{PokemonType.POISON, PokemonType.GROUND}),
    NIDORAN_MALE("Nidoran♂", 32, new PokemonType[]{PokemonType.POISON}),
    NIDORINO("Nidorino", 33, new PokemonType[]{PokemonType.POISON}),
    NIDOKING("Nidoking", 34, new PokemonType[]{PokemonType.POISON, PokemonType.GROUND}),
    CLEFAIRY("Clefairy", 35, new PokemonType[]{PokemonType.FAIRY}),
    CLEFABLE("Clefable", 36, new PokemonType[]{PokemonType.FAIRY}),
    VULPIX("Vulpix", 37, new PokemonType[]{PokemonType.FIRE}),
    NINETALES("Ninetales", 38, new PokemonType[]{PokemonType.FIRE}),
    JIGGLYPUFF("Jigglypuff", 39, new PokemonType[]{PokemonType.NORMAL, PokemonType.FAIRY}),
    WIGGLYTUFF("Wigglytuff", 40, new PokemonType[]{PokemonType.NORMAL, PokemonType.FAIRY}),
    ZUBAT("Zubat", 41, new PokemonType[]{PokemonType.POISON, PokemonType.FLYING}),
    GOLBAT("Golbat", 42, new PokemonType[]{PokemonType.POISON, PokemonType.FLYING}),
    ODDISH("Oddish", 43, new PokemonType[]{PokemonType.GRASS, PokemonType.POISON}),
    GLOOM("Gloom", 44, new PokemonType[]{PokemonType.GRASS, PokemonType.POISON}),
    VILEPLUME("Vileplume", 45, new PokemonType[]{PokemonType.GRASS, PokemonType.POISON}),
    PARAS("Paras", 46, new PokemonType[]{PokemonType.BUG, PokemonType.GRASS}),
    PARASECT("Parasect", 47, new PokemonType[]{PokemonType.BUG, PokemonType.GRASS}),
    VENONAT("Venonat", 48, new PokemonType[]{PokemonType.BUG, PokemonType.POISON}),
    VENOMOTH("Venomoth", 49, new PokemonType[]{PokemonType.BUG, PokemonType.POISON}),
    DIGLETT("Diglett", 50, new PokemonType[]{PokemonType.GROUND}),
    DUGTRIO("Dugtrio", 51, new PokemonType[]{PokemonType.GROUND}),
    MEOWTH("Meowth", 52, new PokemonType[]{PokemonType.NORMAL}),
    PERSIAN("Persian", 53, new PokemonType[]{PokemonType.NORMAL}),
    PSYDUCK("Psyduck", 54, new PokemonType[]{PokemonType.WATER}),
    GOLDUCK("Golduck", 55, new PokemonType[]{PokemonType.WATER}),
    MANKEY("Mankey", 56, new PokemonType[]{PokemonType.FIGHTING}),
    PRIMEAPE("Primeape", 57, new PokemonType[]{PokemonType.FIGHTING}),
    GROWLITHE("Growlithe", 58, new PokemonType[]{PokemonType.FIRE}),
    ARCANINE("Arcanine", 59, new PokemonType[]{PokemonType.FIRE}),
    POLIWAG("Poliwag", 60, new PokemonType[]{PokemonType.WATER}),
    POLIWHIRL("Poliwhirl", 61, new PokemonType[]{PokemonType.WATER}),
    POLIWRATH("Poliwrath", 62, new PokemonType[]{PokemonType.WATER, PokemonType.FIGHTING}),
    ABRA("Abra", 63, new PokemonType[]{PokemonType.PSYCHIC}),
    KADABRA("Kadabra", 64, new PokemonType[]{PokemonType.PSYCHIC}),
    ALAKAZAM("Alakazam", 65, new PokemonType[]{PokemonType.PSYCHIC}),
    MACHOP("Machop", 66, new PokemonType[]{PokemonType.FIGHTING}),
    MACHOKE("Machoke", 67, new PokemonType[]{PokemonType.FIGHTING}),
    MACHAMP("Machamp", 68, new PokemonType[]{PokemonType.FIGHTING}),
    BELLSPROUT("Bellsprout", 69, new PokemonType[]{PokemonType.GRASS, PokemonType.POISON}),
    WEEPINBELL("Weepinbell", 70, new PokemonType[]{PokemonType.GRASS, PokemonType.POISON}),
    VICTREEBEL("Victreebel", 71, new PokemonType[]{PokemonType.GRASS, PokemonType.POISON}),
    TENTACOOL("Tentacool", 72, new PokemonType[]{PokemonType.WATER, PokemonType.POISON}),
    TENTACRUEL("Tentacruel", 73, new PokemonType[]{PokemonType.WATER, PokemonType.POISON}),
    GEODUDE("Geodude", 74, new PokemonType[]{PokemonType.ROCK, PokemonType.GROUND}),
    GRAVELER("Graveler", 75, new PokemonType[]{PokemonType.ROCK, PokemonType.GROUND}),
    GOLEM("Golem", 76, new PokemonType[]{PokemonType.ROCK, PokemonType.GROUND}),
    PONYTA("Ponyta", 77, new PokemonType[]{PokemonType.FIRE}),
    RAPIDASH("Rapidash", 78, new PokemonType[]{PokemonType.FIRE}),
    SLOWPOKE("Slowpoke", 79, new PokemonType[]{PokemonType.WATER, PokemonType.PSYCHIC}),
    SLOWBRO("Slowbro", 80, new PokemonType[]{PokemonType.WATER, PokemonType.PSYCHIC}),
    MAGNEMITE("Magnemite", 81, new PokemonType[]{PokemonType.ELECTRIC, PokemonType.STEEL}),
    MAGNETON("Magneton", 82, new PokemonType[]{PokemonType.ELECTRIC, PokemonType.STEEL}),
    FARFETCHD("Farfetch'd", 83, new PokemonType[]{PokemonType.NORMAL, PokemonType.FLYING}),
    DODUO("Doduo", 84, new PokemonType[]{PokemonType.NORMAL, PokemonType.FLYING}),
    DODRIO("Dodrio", 85, new PokemonType[]{PokemonType.NORMAL, PokemonType.FLYING}),
    SEEL("Seel", 86, new PokemonType[]{PokemonType.WATER}),
    DEWGONG("Dewgong", 87, new PokemonType[]{PokemonType.WATER, PokemonType.ICE}),
    GRIMER("Grimer", 88, new PokemonType[]{PokemonType.POISON}),
    MUK("Muk", 89, new PokemonType[]{PokemonType.POISON}),
    SHELLDER("Shellder", 90, new PokemonType[]{PokemonType.WATER}),
    CLOYSTER("Cloyster", 91, new PokemonType[]{PokemonType.WATER, PokemonType.ICE}),
    GASTLY("Gastly", 92, new PokemonType[]{PokemonType.GHOST, PokemonType.POISON}),
    HAUNTER("Haunter", 93, new PokemonType[]{PokemonType.GHOST, PokemonType.POISON}),
    GENGAR("Gengar", 94, new PokemonType[]{PokemonType.GHOST, PokemonType.POISON}),
    ONIX("Onix", 95, new PokemonType[]{PokemonType.ROCK, PokemonType.GROUND}),
    DROWZEE("Drowzee", 96, new PokemonType[]{PokemonType.PSYCHIC}),
    HYPNO("Hypno", 97, new PokemonType[]{PokemonType.PSYCHIC}),
    KRABBY("Krabby", 98, new PokemonType[]{PokemonType.WATER}),
    KINGLER("Kingler", 99, new PokemonType[]{PokemonType.WATER}),
    VOLTORB("Voltorb", 100, new PokemonType[]{PokemonType.ELECTRIC}),
    ELECTRODE("Electrode", 101, new PokemonType[]{PokemonType.ELECTRIC}),
    EXEGGCUTE("Exeggcute", 102, new PokemonType[]{PokemonType.GRASS, PokemonType.PSYCHIC}),
    EXEGGUTOR("Exeggutor", 103, new PokemonType[]{PokemonType.GRASS, PokemonType.PSYCHIC}),
    CUBONE("Cubone", 104, new PokemonType[]{PokemonType.GROUND}),
    MAROWAK("Marowak", 105, new PokemonType[]{PokemonType.GROUND}),
    HITMONLEE("Hitmonlee", 106, new PokemonType[]{PokemonType.FIGHTING}),
    HITMONCHAN("Hitmonchan", 107, new PokemonType[]{PokemonType.FIGHTING}),
    LICKITUNG("Lickitung", 108, new PokemonType[]{PokemonType.NORMAL}),
    KOFFING("Koffing", 109, new PokemonType[]{PokemonType.POISON}),
    WEEZING("Weezing", 110, new PokemonType[]{PokemonType.POISON}),
    RHYHORN("Rhyhorn", 111, new PokemonType[]{PokemonType.GROUND, PokemonType.ROCK}),
    RHYDON("Rhydon", 112, new PokemonType[]{PokemonType.GROUND, PokemonType.ROCK}),
    CHANSEY("Chansey", 113, new PokemonType[]{PokemonType.NORMAL}),
    TANGELA("Tangela", 114, new PokemonType[]{PokemonType.GRASS}),
    KANGASKHAN("Kangaskhan", 115, new PokemonType[]{PokemonType.NORMAL}),
    HORSEA("Horsea", 116, new PokemonType[]{PokemonType.WATER}),
    SEADRA("Seadra", 117, new PokemonType[]{PokemonType.WATER}),
    GOLDEEN("Goldeen", 118, new PokemonType[]{PokemonType.WATER}),
    SEAKING("Seaking", 119, new PokemonType[]{PokemonType.WATER}),
    STARYU("Staryu", 120, new PokemonType[]{PokemonType.WATER}),
    STARMIE("Starmie", 121, new PokemonType[]{PokemonType.WATER, PokemonType.PSYCHIC}),
    MR_MIME("Mr. Mime", 122, new PokemonType[]{PokemonType.PSYCHIC, PokemonType.FAIRY}),
    SCYTHER("Scyther", 123, new PokemonType[]{PokemonType.BUG, PokemonType.FLYING}),
    JYNX("Jynx", 124, new PokemonType[]{PokemonType.ICE, PokemonType.PSYCHIC}),
    ELECTABUZZ("Electabuzz", 125, new PokemonType[]{PokemonType.ELECTRIC}),
    MAGMAR("Magmar", 126, new PokemonType[]{PokemonType.FIRE}),
    PINSIR("Pinsir", 127, new PokemonType[]{PokemonType.BUG}),
    TAUROS("Tauros", 128, new PokemonType[]{PokemonType.NORMAL}),
    MAGIKARP("Magikarp", 129, new PokemonType[]{PokemonType.WATER}),
    GYARADOS("Gyarados", 130, new PokemonType[]{PokemonType.WATER, PokemonType.FLYING}),
    LAPRAS("Lapras", 131, new PokemonType[]{PokemonType.WATER, PokemonType.ICE}),
    DITTO("Ditto", 132, new PokemonType[]{PokemonType.NORMAL}),
    EEVEE("Eevee", 133, new PokemonType[]{PokemonType.NORMAL}),
    VAPOREON("Vaporeon", 134, new PokemonType[]{PokemonType.WATER}),
    JOLTEON("Jolteon", 135, new PokemonType[]{PokemonType.ELECTRIC}),
    FLAREON("Flareon", 136, new PokemonType[]{PokemonType.FIRE}),
    PORYGON("Porygon", 137, new PokemonType[]{PokemonType.NORMAL}),
    OMANYTE("Omanyte", 138, new PokemonType[]{PokemonType.ROCK, PokemonType.WATER}),
    OMASTAR("Omastar", 139, new PokemonType[]{PokemonType.ROCK, PokemonType.WATER}),
    KABUTO("Kabuto", 140, new PokemonType[]{PokemonType.ROCK, PokemonType.WATER}),
    KABUTOPS("Kabutops", 141, new PokemonType[]{PokemonType.ROCK, PokemonType.WATER}),
    AERODACTYL("Aerodactyl", 142, new PokemonType[]{PokemonType.ROCK, PokemonType.FLYING}),
    SNORLAX("Snorlax", 143, new PokemonType[]{PokemonType.NORMAL}),
    ARTICUNO("Articuno", 144, new PokemonType[]{PokemonType.ICE, PokemonType.FLYING}),
    ZAPDOS("Zapdos", 145, new PokemonType[]{PokemonType.ELECTRIC, PokemonType.FLYING}),
    MOLTRES("Moltres", 146, new PokemonType[]{PokemonType.FIRE, PokemonType.FLYING}),
    DRATINI("Dratini", 147, new PokemonType[]{PokemonType.DRAGON}),
    DRAGONAIR("Dragonair", 148, new PokemonType[]{PokemonType.DRAGON}),
    DRAGONITE("Dragonite", 149, new PokemonType[]{PokemonType.DRAGON, PokemonType.FLYING}),
    MEWTWO("Mewtwo", 150, new PokemonType[]{PokemonType.PSYCHIC}),
    MEW("Mew", 151, new PokemonType[]{PokemonType.PSYCHIC});

    private final String name;
    private final int value;
    private final PokemonType[] types;

    private PokemonID(String name, int value, PokemonType[] types) {
        this.name = name;
        this.value = value;
        this.types = types;
    }

    public String getName() {
        return name;
    }

    public int getValue() {
        return value;
    }

    public PokemonType[] getTypes() {
        return types;
    }
}
